[tool.poetry]
name = "monetdb_profiler_tools"
version = "0.1.0"
description = ""
authors = ["Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
funcy = "^1.13"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-runner = "^5.2"
tox = "^3.14"
flake8 = "^3.7"
coverage = "^4.5"
rope = "^0.14.0"
pyflakes = "^2.1"
mccabe = "^0.6.1"
pycodestyle = "^2.5"
pydocstyle = "^4.0"
yapf = "^0.28.0"
python-language-server = {version = "^0.30.0", extras = ["all"]}
pymonetdb = {path = "/home/kutsurak/work/monet/sources/pymonetdb/"}
[tool.poetry.scritps]
stethoscope = 'monetdb_profiler_tools.stethoscope:stethoscope'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
