name: Release pystethoscope
on:
  push:
    tags:
      - *

jobs:
  release-job:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipfile
        pip install poetry
        poetry install
    - name: Publish on PyPI
      env:
        # PYPI_TOKEN: ${{ secrets.PYPI_PYSTETHOSCOPE_PUBLISH_TOKEN }}
        PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        poetry publish --build -u __token__ -p $PYPI_TOKEN -r testpypi
